### PR TITLE
fix darkening icons in android api 30+

### LINKED ISSUE #12: darkButtons property is not working on Android 13
Hi,

It looks like darkButtons property is not working on Android 13. The navigation bar buttons are always white.
I have tried on Android 10 and it's working fine.

Is it possible to make it working on Android 13 ?

Thanks for your work 😄

### PR DESCRIPTION
**Pull request by sabereen**
closes #12

### CODE REVIEW

**Comment by WilliamFischer** [comment]
Thanks @sabereen ! @hugotomazi can this be merged in ASAP please? Otherwise how can i use this pull commit in my package.json in the meantime?

**Comment by sabereen** [comment]
> Thanks @sabereen ! @hugotomazi can this be merged in ASAP please? Otherwise how can i use this pull commit in my package.json in the meantime?

I am using [patch-package](https://www.npmjs.com/package/patch-package) in the meantime!

This is my patch file:
```patch
diff --git a/node_modules/@hugotomazi/capacitor-navigation-bar/android/src/main/java/br/com/tombus/capacitor/plugin/navigationbar/NavigationBarPlugin.java b/node_modules/@hugotomazi/capacitor-navigation-bar/android/src/main/java/br/com/tombus/capacitor/plugin/navigationbar/NavigationBarPlugin.java
index e831ad2..4d91de6 100644
--- a/node_modules/@hugotomazi/capacitor-navigation-bar/android/src/main/java/br/com/tombus/capacitor/plugin/navigationbar/NavigationBarPlugin.java
+++ b/node_modules/@hugotomazi/capacitor-navigation-bar/android/src/main/java/br/com/tombus/capacitor/plugin/navigationbar/NavigationBarPlugin.java
@@ -7,6 +7,9 @@ import android.app.Activity;
 import android.view.Window;
 import android.view.WindowManager;
 
+import androidx.core.view.WindowCompat;
+import androidx.core.view.WindowInsetsControllerCompat;
+
 import com.getcapacitor.JSObject;
 import com.getcapacitor.Plugin;
 import com.getcapacitor.PluginCall;
@@ -112,15 +115,10 @@ public class NavigationBarPlugin extends Plugin {
                     }
 
                     Window window = getActivity().getWindow();
-                    int options = window.getDecorView().getSystemUiVisibility() | WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS;
+                    WindowInsetsControllerCompat windowInsetsControllerCompat = WindowCompat.getInsetsController(window, window.getDecorView());
 
-                    if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O && darkButtons) {
-                        options |= View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
-                    } else {
-                        options &= ~View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
-                    }
+                    windowInsetsControllerCompat.setAppearanceLightNavigationBars(!darkButtons);
 
-                    window.getDecorView().setSystemUiVisibility(options);
                     window.setNavigationBarColor(Color.parseColor(color));
                     String newColor = String.format("#%08X", (0xFFFFFFFF & window.getNavigationBarColor()));
 

```

**Comment by hugotomazi** [comment]
Hello @sabereen! 
First of all thank you very much for your contribution! Before approving, can you tell me if this solution maintains support for old versions of android? Could you test this solution on an older version of android to validate this?

**Comment by sabereen** [comment]
Yes, I used `WindowCompat` class, that is the backward compatible version of `Window` class. Also I tested it on several modern and legacy devices and it was OK.

**Comment by sawaca96** [comment]
@hugotomazi  waiting merge....🙏

**Comment by jseongee** [comment]
@hugotomazi i am waiting too 😭

**Comment by hugotomazi** [comment]
Hey @sabereen @sawaca96 @jskimweb @WilliamFischer ! Can you post pictures showing the problem? In my tests, the "darkButtons" functionality is working normally in APIs level 30+ with the exception of API 33 (apparently the API adjusts the button color automatically based on the background color of the navigation bar. That would be the problem you are facing?).

example

**Comment by sabereen** [comment]
Are you sure your SDK target is greater than 30?
If the app is built by old SDK targets, there is no problem, but GooglePlay does not accept apps built by old SDK targets.

**Comment by hugotomazi** [comment]
Okay, now I understand the problem. We agree that the Plugin needs a method overhaul.
I will create a new branch to make these fixes and your change will be added to it. Thank you very much @sabereen !

**Comment by frederikheld** [comment]
@hugotomazi I have the same issue but it only appears if I have Android set to use the 3 button navigation. For gesture navigation the little bar changes the color automatically.

**Pull request merged**
