### PR TITLE
Updated To Capacitor V4

### PR DESCRIPTION
**Pull request by keyurboss**

### CODE REVIEW

**Comment by I-am-abdulazeez** [comment]
Hi, any updates on this

```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: adsup@0.0.1
npm ERR! Found: @capacitor/core@4.0.1
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"4.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.0.0" from @hugotomazi/capacitor-navigation-bar@1.1.1
npm ERR! node_modules/@hugotomazi/capacitor-navigation-bar
npm ERR!   @hugotomazi/capacitor-navigation-bar@"*" from the root project
```

**Comment by keyurboss** [comment]
I will look into this.

**Comment by keyurboss** [comment]
Can you tell me the steps to reproduce??

**Comment by I-am-abdulazeez** [comment]
Hi, @rpsoftech 

generate an `ionic-vue` project, 

run `npm i @hugotomazi/capacitor-navigation-bar` 

dep should look like this

 ```
"@capacitor/android": "4.0.1",
    "@capacitor/app": "4.0.1",
    "@capacitor/core": "4.0.1",
    "@capacitor/haptics": "4.0.1",
    "@capacitor/keyboard": "4.0.1",
    "@capacitor/status-bar": "^4.0.1",

```

You should get the above error

**Comment by keyurboss** [comment]
You are getting the error because Lib is not updated on NPM

Once PR is merged and released on NPM then you will be able to use this.

Meanwhile, you can use this 

```npm i https://github.com/rpsoftech/capacitor-navigation-bar#Capv4```

**Comment by keyurboss** [comment]
I have updated CI script to use JDK 11.

Please Approve so CI task can run.

**Review by keyurboss — COMMENTED** [review]
DONE

**Comment by keyurboss** [comment]
Hi @I-am-abdulazeez 
Did you check the steps I mentioned

**Comment by mpkasp** [comment]
Breaks iOS Podfile, when running `ionic cap sync` I get:

```
[capacitor] ✖ Updating iOS native dependencies with pod install - failed!
[capacitor] ✖ update ios - failed!
[capacitor] [error] Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
[capacitor]         Analyzing dependencies
[capacitor]         [!] No podspec found for `RpsCapacitorNavigationBar` in `../../node_modules/@rps/capacitor-navigation-bar`
```

Looks like the podspec is named `HugotomaziCapacitorNavigationBar` instead of `RpsCapacitorNavigationBar`

**Comment by hugotomazi** [comment]
Hello guys, I apologize for the delay in reviewing this PR, I'll do the proper tests and if it's working normally I'll make the new version available on NPM.

@mpkasp That will solve your problem.

**Comment by keyurboss** [comment]
> Breaks iOS Podfile, when running `ionic cap sync` I get:
> 
> ```
> [capacitor] ✖ Updating iOS native dependencies with pod install - failed!
> [capacitor] ✖ update ios - failed!
> [capacitor] [error] Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
> [capacitor]         Analyzing dependencies
> [capacitor]         [!] No podspec found for `RpsCapacitorNavigationBar` in `../../node_modules/@rps/capacitor-navigation-bar`
> ```
> 
> Looks like the podspec is named `HugotomaziCapacitorNavigationBar` instead of `RpsCapacitorNavigationBar`

Sorry For The inconvenience.

In capacitor it is working fine so I did not checked also there is no ios support in this plugin

**Comment by hugotomazi** [comment]
I did the tests and appropriate adaptations in the demo project, all OK. Thanks @rpsoftech, @keyur39 and everyone involved in the tests, your feedback was essential!

@mpkasp try to update to version 2.0.0 please.

**Pull request merged**
